version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: echo "Time report" # run the `echo` command
      - run: 
        command: npm run test
        working_directory: frontend 
      # - run: npm run deploy